name: "Cherry"

on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/cherry')
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Add comment to PR
        uses: actions/github-script@v6
        with:
            script: |
              const name = '${{ github.workflow   }}';
              const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
              const body = `Ohhi! Will try to cherry-pick this!`;
  
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              })